# Generated by Django 3.2.5 on 2021-10-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0003_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
