# Generated by Django 3.2.5 on 2021-10-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(default=0),
        ),
    ]
