# Generated by Django 3.2.5 on 2021-10-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0006_profile_bmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg')], max_length=50)),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
