# Generated by Django 3.2.5 on 2021-10-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0008_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-veg')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('Gain-Weight', 'Gain Weight'), ('Lose-Weight', 'Lose Weight')], max_length=50),
        ),
    ]
