# Generated by Django 3.2.5 on 2021-10-14 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0009_auto_20211014_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient1', models.CharField(max_length=50)),
                ('ingredient2', models.CharField(max_length=50)),
                ('ingredient3', models.CharField(max_length=50)),
                ('ingredient4', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
